project_id = "jvmkyqrwhbcdkdsccezg"

[functions.hotelbeds-search]
verify_jwt = false

[functions.hotelbeds-booking]
verify_jwt = false

[functions.amadeus-search]
verify_jwt = false

[functions.post-tweet]
verify_jwt = false

[functions.send-ad-email]
verify_jwt = false

[functions.send-booking-invoice]
verify_jwt = false
